[Windows] Re-implement Windows support using C++
DoubleSymmetry/react-native-track-player pull request #1159
Opened 2021-04-22 11:41 UTC by tritao

This PR removes the existing C# implementation of the module and updates it with an almost literal C++ port with some updates to use JSValue functionality instead of JSON types internally.

This work is being done on behalf of Microsoft in an effort to update modules.

2021-04-22 19:50 UTC, asklar requested changes
doing a first pass : ) main feedback is: 
- discourage the use of raw pointers (use shared_ptr and the likes for relationships where two objects need to know about each other, or identify whether they can be merged into the same object)
- clean up the private/public boundary for these structs
- take input strings (or any complex type) by ref
- use constexpr for constant values known at compile time
- error checking missing in some cases, consider providing meaningful error messages

2021-04-22 19:50 UTC, asklar commented on windows/RNTrackPlayer/Logic/Utils.cpp
> +        return Uri(winrt::to_hstring(val.AsObject()["uri"].AsString()));
what if uri is not defined in the object? (probably want to fail)

2021-04-23 22:37 UTC, rectified95 commented on windows/RNTrackPlayer/Logic/Metadata.cpp
> +    , jumpInterval(15)
(nit) Slightly odd formatting - move the commas to end of line?

2021-04-23 22:38 UTC, rectified95 commented on windows/RNTrackPlayer/Logic/Metadata.cpp
> +        play = Utils::ContainsInt(capabilities, (int)Capability::Play);
(nit) prefer static_cast in modern c++

2021-04-23 22:39 UTC, rectified95 commented on windows/RNTrackPlayer/Logic/Metadata.cpp
> +        if (controls != nullptr) UpdateCapabilities();
(nit) use curly brackets for consistent styling of if-blocks

2021-04-23 22:39 UTC, rectified95 commented on windows/RNTrackPlayer/Logic/Metadata.cpp
> +
remove blank line

2021-04-23 22:41 UTC, rectified95 commented on windows/RNTrackPlayer/Logic/Metadata.h
> +        MediaManager* manager;
+1 on this, use a pair of std:shared_ptr and std::weak_ptr

2021-04-23 22:46 UTC, rectified95 commented on windows/RNTrackPlayer/RNTrackPlayer.cpp
> +    for(const JSValue& id : arr)
missing space for" "(

2021-04-26 18:24 UTC, tritao commented
Updated the PR with the review feedback.

I opted to use a `std::unique_ptr` since there is no need for shared ownership `std::shared_ptr`, and there is also no need for the lifecycle tracking feature of the `weak_ptr`. Hope that's OK, if not, I can change it.

Let me know if there is anything else.

2021-04-28 17:30 UTC, tritao commented
Upon further testing, found another couple issues. 

Pushed fixes for incorrect duration calcs as well as the loading callback not working.

2021-05-04 19:58 UTC, asklar commented
@tritao please let us know when it's ready to review again : )

2021-05-04 20:11 UTC, tritao commented
It should be ready to go now.

2021-05-29 16:08 UTC, dcvz commented
thank you for this contribution @tritao! I will try this out soon and see how to best get it into our ongoing efforts of v2.

2021-05-30 11:23 UTC, dcvz commented
@tritao it looks pretty solid to me although my c++ is not super amazing.
Eventually it would be great to add windows to the example app we have in the repository that can be validated by the CI.

Currently we're working hard to get v2 shipped and released.. in there we introduced one big change vs the current version which is we changed the queue modification methods: `add`, `remove`, `skipTo`, etc.. to be index based instead of ID based.

Would you be interested in lining this up with our current `main` branch (where we're working on v2) and change the methods to be index based?

2021-06-09 14:38 UTC, tritao commented
@dcvz Sorry for delay in getting back to you, had to discuss with manager.

I see you already opened another PR with some WIP, so I'll close this one.

2021-06-09 14:38 UTC, closed without merging

2021-06-09 14:40 UTC, dcvz commented
Followed up in the new PR @tritao could still benefit from some C++ experience to get this effort in

2021-07-01 20:43 UTC, stmoy commented
Linking up the new PR: https://github.com/DoubleSymmetry/react-native-track-player/pull/1180