Feat: Remove previous track on queue
doublesymmetry/react-native-track-player pull request #1307
Opened 2021-10-14 11:46 UTC by ithustle

This feature will help to anyone who want implements their own shuffle mode. The reason of this method was built its because `.remove()` for iOS doesn't work as expected when trying to remove bulk tracks.

2021-11-05 11:06 UTC, dcvz commented
Thanks for the PR @ithustle , will take a look at it soon!

2021-11-09 05:53 UTC, rogerespinoza commented
Hello, maybe it will help you  
`tracksRemoveIndex.forEach(async (element) => {
     await TrackPlayer.remove([0]);
  });`

2022-05-06 12:59 UTC, ithustle commented
@bradleyflood, yes off course!

2022-05-06 13:20 UTC, bradleyflood requested changes
Good point @jspizziri I hadn’t seen your earlier message. 

Need to confirm functionality and add Android support. 

@dcvz

2022-05-06 17:46 UTC, dcvz commented
@bradleyflood @jspizziri @ithustle I'm not opposed to this addition but there's some things to keep in mind:

1. We need to add support for other platforms too.

2. It's a bit more complicated to remove previous tracks because it changes the index of the currently playing track.. so we'll need to make sure this doesn't break something. SwiftAudioEx already has support for this but not Android. Though we already support removing indexes smaller than the current one.. so there's precedence.

3. We'll want to make this change against the current `main`

2022-05-06 21:56 UTC, jspizziri commented
@ithustle Looks like you're cleared for takeoff. I can assist with initial review and provide some implementation guidance along the way should you need it.

2022-05-06 22:07 UTC, ithustle commented
@jspizziri I appreciate that. I'd like to start updating the doc. I couldn't find the MD file.

2022-05-06 22:47 UTC, jspizziri commented
@ithustle You can find it under `docs/docs/api/functions/queue.md`

2022-06-24 20:41 UTC, jspizziri commented
@ithustle I'm closing this since you opened another PR concerning the same feature with docs. Let's keep all commits concerning a feature on the same PR.

2022-06-24 20:41 UTC, closed without merging