fix: Fire “playback-changed-event” with single track
doublesymmetry/react-native-track-player pull request #1757
Opened 2022-09-27 10:22 UTC by mpivchev

2022-09-27 12:01 UTC, jspizziri commented
@mpivchev the commit history on this branch seems a little weird. I'm guessing you branched off of a branch that has since been merged & squashed?

2022-09-27 12:04 UTC, jspizziri commented on android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
> +                    if (it == AudioPlayerState.ENDED && player.nextItem == null) {
@mpivchev this looks good. One small thing: can we move the emit of the queue-ended to be _after_ the track changed? I know they're async so there's no guarantee, but I'm guessing more times than not they'll arrive in order and this is the ordering of iOS (track changed first, then queue ended)

2022-09-27 12:11 UTC, mpivchev commented on android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
> +                    if (it == AudioPlayerState.ENDED && player.nextItem == null) {
Done :)

2022-09-27 12:18 UTC, jspizziri requested changes
@mpivchev something doesn't seem quite right with this fix. 

My testing shows that the stock `example` app emits the following events when the app loads:

```
 LOG  Event.PlaybackTrackChanged {"position": 0, "track": 0}
 LOG  Event.PlaybackTrackChanged {"nextTrack": 0, "position": 0}
 LOG  Event.PlaybackTrackChanged {"position": 0, "track": 0}
 LOG  Event.PlaybackTrackChanged {"position": 0, "track": 0}
 ```
 
 This is prior to any interaction with the queue, only adding tracks. It seems that conditional was preventing duplicate events from being fired.

2022-09-27 14:43 UTC, mpivchev commented
That's unfortunate. Will look into another solution

2022-09-28 16:28 UTC, mpivchev commented
@jspizziri Do these duplicate events produce any unwanted results? I think it's ok to leave them firing if that's the case. But welcome to discuss this.

2022-09-28 16:29 UTC, jspizziri commented
@mpivchev users are keying off of these events to do various things in their apps. If there are duplicates I'd imagine it will certainly produce unwanted results for them, yes.

2023-01-24 17:13 UTC, closed without merging

2023-01-24 17:13 UTC, jspizziri commented
I think this can be closed with the new events structure introduced by https://github.com/doublesymmetry/react-native-track-player/pull/1713